### ISSUE TITLE
Reusing `adk run` and `adk web` with custom Runners (and other custom services)

### ISSUE THREAD

**Issue by ksachdeva** [google/adk-python#1181]
**Is your feature request related to a problem? Please describe.**

I loved the dev specific tools (running via the cli or web) that are part of adk. However, they are good enough for simple agents. Anything that requires reliance on other custom objects (e.g. Session, artificate service, Custom/Extended Runner etc) requires one to write a custom script and thereby not utilizing the dev tools that come built in. 

**Describe the solution you'd like**

While it would be difficult to specific the custom runner or service to use on CLI, refactoring the functions in 
https://github.com/google/adk-python/blob/main/src/google/adk/cli/cli.py
such as `run_interactively` and `run_cli` could enable one to directly use them from their custom script (entrypoint).

**Describe alternatives you've considered**
Alternatives require duplication of code

**Comment by lvcarnevalli** [comment]
I have the same question, if it is possible to debug (`adk web`) with the custom Runner.

**Comment by klateefa** [comment]
Hi @ksachdeva  and thanks to everyone who participated in this thread.

We're currently doing some housekeeping on our issue tracker. Given the rapid pace of development and the number of updates since this was last active, there's a good chance this issue has been resolved in a newer version. To help us keep our backlog focused on current issues, we are closing this as stale.

If you're still facing this problem, could you please update to the very latest version of the library and confirm the issue still exists? If it does, please comment here, and we will be happy to reopen this issue and investigate further.

Thanks for your contribution and understanding!

**Comment by b-gran** [comment]
Hi @klateefa, I believe this issue is still unresolved. The docs don't cover using `adk run` and `adk web` with custom Runners.
