### ISSUE TITLE
ADK MCP Client should support the get images method

### ISSUE THREAD

**Issue by stfines-clgx** [google/adk-python#1221]
In [this](https://github.com/google/adk-python/issues/684#issuecomment-2878571641) it is mentioned that only get tools is supported by the adk. Get image support is also needed for those mcp servers which support.

**Comment by klateefa** [comment]
Hi @stfines-clgx  and thanks to everyone who participated in this thread.

We're currently doing some housekeeping on our issue tracker. Given the rapid pace of development and the number of updates since this was last active, there's a good chance this issue has been resolved in a newer version. To help us keep our backlog focused on current issues, we are closing this as stale.

If you're still facing this problem, could you please update to the very latest version of the library and confirm the issue still exists? If it does, please comment here, and we will be happy to reopen this issue and investigate further.

Thanks for your contribution and understanding!

**Comment by stfines-clgx** [comment]
ADK Still does not support the MCP Protocol completely. It is still tools only.

**Comment by salvatore-cipolla** [comment]
Any news on this?
